In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

csv_path = r'C:\Users\Christian and Gemma\OneDrive\Graduate School\ANA680\Week 4\chip_dataset.csv'
data = pd.read_csv(csv_path)
 
# Scaling Variables Down to 0-10 Ranges:
# (I had to drop the spaces in the FP*GFLOPS variables for ease of coding)
df_norm = data.drop(['Index','Product','Type','Release Date','Die Size (mm^2)',
                     'Transistors (million)','Foundry','Vendor','FP16GFLOPS','FP32GFLOPS',
                     'FP64GFLOPS'], axis=1)
df_raw = (df_norm-df_norm.min())/(df_norm.max()-df_norm.min()) * 10
df_raw = pd.concat((df_raw, data.FP64GFLOPS), 1)

df = df_raw.dropna()

# input
x = df.iloc[:, [0,1,2]].values
# x[:, 1] = -x[:, 1]
  
# output
y = df.iloc[:, 3].values

#convert y values to categorical values
lab = preprocessing.LabelEncoder()
y = lab.fit_transform(y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

# note: feature scaling not required as all feature values have same (1-10) range, so one will
# not dominate the others

regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)

# Predict on dataset which model has not seen before
y_pred = regressor.fit(X_train, y_train).predict(X_test)

y_pred_int = np.asarray(y_pred, dtype = 'int')

cm = confusion_matrix(y_test, y_pred_int)
  
print ("Confusion Matrix : \n", cm)
print ("Accuracy : ", accuracy_score(y_test, y_pred_int))

Confusion Matrix : 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 1]]
Accuracy :  0.10204081632653061


C:\Users\CHRIST~1\AppData\Local\Temp/ipykernel_25844/1661823713.py:16: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  df_raw = pd.concat((df_raw, data.FP64GFLOPS), 1)


In [9]:
import pandas as pd

csv_path = r'C:\Users\Christian and Gemma\OneDrive\Graduate School\ANA680\breast-cancer-wisconsin.csv'
df = pd.read_csv(csv_path)

df.head()

SampleNo  Thickness  Size  Shape  Adhesion  Epithelial Nuclei  Chromatin  \
0   1000025          5     1      1         1           2      1          3   
1   1002945          5     4      4         5           7     10          3   
2   1015425          3     1      1         1           2      2          3   
3   1016277          6     8      8         1           3      4          3   
4   1017023          4     1      1         3           2      1          3   

   Nucleoli  Mitoses  Class  
0         1        1      2  
1         2        1      2  
2         1        1      2  
3         7        1      2  
4         1        1      2